- name: variables from files
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: print varibles
    ansible.builtin.debug:
      msg: "My name is {{NAME}},  my locaion is: {{LOCATION}}"

   