- name: variables from files
  hosts: localhost
  vars_files:
  - var1.yaml
 tasks:
 - name: print varibles calling from files 
   ansible.builtin.debug:
     msg: "My name is {{NAME}} and my locaion is: {{LOCATION}}"

   