- name: command line variables usage in ansible
  hosts: localhost
  tasks:
  - name: get variable values from command line
    ansible.builtin.debug:
      msg: "I am working in {{COMPANY}} product based company"

#use below command to execute above code
#ansible-playbook -e ansible_user=centos -e anisble_password=DevOps321 -e COMPANY=SYNCRON 10-vars-args.yaml