- name: declare variables at all levels and test its precedence
  hosts: mongodb
  vars:
    COUNTRY: India-play
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: Please enter country name
    private: false
  tasks:
  - name: declare variable at task level
    vars:
      COUNTRY: India-task-level    
    ansible.builtin.debug:
      msg: "Country name is: {{COUNTRY}}"


