- name: variables at task level
  hosts: localhost
  vars:
  - name: "Syncron"
    location: "Hyderabad"
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Play level values: name is {{name}} and location is {{location}}"
  - name: inherit values from playlevel
    vars:
    - name: "TCS"
      country: "India"
    ansible.builtin.debug:
      msg: "task level values: name {{name}}, location {{location}} and country is {{country}}"