- name: checking when condition
  hosts: localhost
  vars:
    NAME: AWS
  tasks:
  - name: when condition usage in ansible
    ansible.builtin.debug:
      msg: "name is {{NAME}}"
    when: NAME == "DevOps"