- name: variables precedence in Ansible
  hosts: mongodb
  # vars:
  #   company: SYNCRON-play-level
  # vars_files:
  # - variables.yaml
  # vars_prompt:
  # - name: company
  #   prompt: please enter your company name
  #   private: false
  tasks:
    - name: variables at task level
      ansible.builtin.debug:
        msg: "company name is {{company}}"


  #vars precedence:
  #1.arguement level
  #2.task level
  #3.file level variable
  #4.prompt level
  #5.play-lelel